"""is_erc20 default None

Revision ID: 22d39ca864b9
Revises: 30457445bfb9
Create Date: 2024-07-09 15:56:08.114998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22d39ca864b9'
down_revision: Union[str, None] = '30457445bfb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'is_erc20',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'is_erc20',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
