"""nullable standard in contract model

Revision ID: 30457445bfb9
Revises: f63956dc7849
Create Date: 2024-07-09 15:40:01.930212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30457445bfb9'
down_revision: Union[str, None] = 'f63956dc7849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'standard_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'standard_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
