"""extension model

Revision ID: 72179d204cfd
Revises: f04a7bda7abc
Create Date: 2024-07-10 11:45:28.463766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72179d204cfd'
down_revision: Union[str, None] = 'f04a7bda7abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extensions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('standard_id', sa.Integer(), nullable=True),
    sa.Column('is_parsed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('function__extension',
    sa.Column('function_id', sa.Integer(), nullable=False),
    sa.Column('extension_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['extension_id'], ['extensions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['function_id'], ['functions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('function__extension')
    op.drop_table('extensions')
    # ### end Alembic commands ###
