"""delete contract__standard model

Revision ID: f04a7bda7abc
Revises: 1b8e9faa7771
Create Date: 2024-07-09 16:49:19.081498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f04a7bda7abc'
down_revision: Union[str, None] = '1b8e9faa7771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contract__standard')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract__standard',
    sa.Column('contract_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('standard_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name='contract__standard_contract_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], name='contract__standard_standard_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='contract__standard_pkey')
    )
    # ### end Alembic commands ###
