"""unique standard name and contract address

Revision ID: f63956dc7849
Revises: 2672ba93a1d0
Create Date: 2024-07-09 13:41:43.379859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f63956dc7849'
down_revision: Union[str, None] = '2672ba93a1d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'contracts', ['contract_address'])
    op.create_unique_constraint(None, 'standards', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'standards', type_='unique')
    op.drop_constraint(None, 'contracts', type_='unique')
    # ### end Alembic commands ###
